/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTraineesRouteImport } from './routes/_authenticated/trainees'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCoordinatorRotaRouteImport } from './routes/_authenticated/coordinator.rota'
import { Route as AuthenticatedCoordinatorLeaveRouteImport } from './routes/_authenticated/coordinator.leave'
import { Route as AuthenticatedAdminTheatresRouteImport } from './routes/_authenticated/admin.theatres'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedCalendarStaffStaffIdRouteImport } from './routes/_authenticated/calendar.staff.$staffId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTraineesRoute = AuthenticatedTraineesRouteImport.update({
  id: '/trainees',
  path: '/trainees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoordinatorRotaRoute =
  AuthenticatedCoordinatorRotaRouteImport.update({
    id: '/coordinator/rota',
    path: '/coordinator/rota',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoordinatorLeaveRoute =
  AuthenticatedCoordinatorLeaveRouteImport.update({
    id: '/coordinator/leave',
    path: '/coordinator/leave',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTheatresRoute =
  AuthenticatedAdminTheatresRouteImport.update({
    id: '/admin/theatres',
    path: '/admin/theatres',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarStaffStaffIdRoute =
  AuthenticatedCalendarStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/me': typeof AuthenticatedMeRoute
  '/trainees': typeof AuthenticatedTraineesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/me': typeof AuthenticatedMeRoute
  '/trainees': typeof AuthenticatedTraineesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/trainees': typeof AuthenticatedTraineesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/_authenticated/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/_authenticated/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/_authenticated/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/chat'
    | '/leave'
    | '/me'
    | '/trainees'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/theatres'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/calendar/staff/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/calendar'
    | '/chat'
    | '/leave'
    | '/me'
    | '/trainees'
    | '/'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/theatres'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/calendar/staff/$staffId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/leave'
    | '/_authenticated/me'
    | '/_authenticated/trainees'
    | '/_authenticated/'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/theatres'
    | '/_authenticated/coordinator/leave'
    | '/_authenticated/coordinator/rota'
    | '/_authenticated/calendar/staff/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainees': {
      id: '/_authenticated/trainees'
      path: '/trainees'
      fullPath: '/trainees'
      preLoaderRoute: typeof AuthenticatedTraineesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/rota': {
      id: '/_authenticated/coordinator/rota'
      path: '/coordinator/rota'
      fullPath: '/coordinator/rota'
      preLoaderRoute: typeof AuthenticatedCoordinatorRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/leave': {
      id: '/_authenticated/coordinator/leave'
      path: '/coordinator/leave'
      fullPath: '/coordinator/leave'
      preLoaderRoute: typeof AuthenticatedCoordinatorLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/theatres': {
      id: '/_authenticated/admin/theatres'
      path: '/admin/theatres'
      fullPath: '/admin/theatres'
      preLoaderRoute: typeof AuthenticatedAdminTheatresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/staff/$staffId': {
      id: '/_authenticated/calendar/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/calendar/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedCalendarStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
  }
}

interface AuthenticatedCalendarRouteChildren {
  AuthenticatedCalendarStaffStaffIdRoute: typeof AuthenticatedCalendarStaffStaffIdRoute
}

const AuthenticatedCalendarRouteChildren: AuthenticatedCalendarRouteChildren = {
  AuthenticatedCalendarStaffStaffIdRoute:
    AuthenticatedCalendarStaffStaffIdRoute,
}

const AuthenticatedCalendarRouteWithChildren =
  AuthenticatedCalendarRoute._addFileChildren(
    AuthenticatedCalendarRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedTraineesRoute: typeof AuthenticatedTraineesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTheatresRoute: typeof AuthenticatedAdminTheatresRoute
  AuthenticatedCoordinatorLeaveRoute: typeof AuthenticatedCoordinatorLeaveRoute
  AuthenticatedCoordinatorRotaRoute: typeof AuthenticatedCoordinatorRotaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedTraineesRoute: AuthenticatedTraineesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTheatresRoute: AuthenticatedAdminTheatresRoute,
  AuthenticatedCoordinatorLeaveRoute: AuthenticatedCoordinatorLeaveRoute,
  AuthenticatedCoordinatorRotaRoute: AuthenticatedCoordinatorRotaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
