/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAuditToolRouteImport } from './routes/api/audit-tool'
import { Route as AuthenticatedWellbeingRouteImport } from './routes/_authenticated/wellbeing'
import { Route as AuthenticatedTraineesRouteImport } from './routes/_authenticated/trainees'
import { Route as AuthenticatedRecognitionRouteImport } from './routes/_authenticated/recognition'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedGlossaryRouteImport } from './routes/_authenticated/glossary'
import { Route as AuthenticatedExceptionsRouteImport } from './routes/_authenticated/exceptions'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedRobustnessIndexRouteImport } from './routes/_authenticated/robustness.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedTraineesStartDateAuditRouteImport } from './routes/_authenticated/trainees.start-date-audit'
import { Route as AuthenticatedTraineesStaffIdRouteImport } from './routes/_authenticated/trainees.$staffId'
import { Route as AuthenticatedStaffWorkingPatternsRouteImport } from './routes/_authenticated/staff.working-patterns'
import { Route as AuthenticatedRobustnessSimulateRouteImport } from './routes/_authenticated/robustness.simulate'
import { Route as AuthenticatedRobustnessPoacAuditRouteImport } from './routes/_authenticated/robustness.poac-audit'
import { Route as AuthenticatedRobustnessListFeasibilityRouteImport } from './routes/_authenticated/robustness.list-feasibility'
import { Route as AuthenticatedRobustnessLastMinuteChangesRouteImport } from './routes/_authenticated/robustness.last-minute-changes'
import { Route as AuthenticatedRobustnessConsultantFeasibilityRouteImport } from './routes/_authenticated/robustness.consultant-feasibility'
import { Route as AuthenticatedRobustnessConsultantAuditsRouteImport } from './routes/_authenticated/robustness.consultant-audits'
import { Route as AuthenticatedLeaveForecastRouteImport } from './routes/_authenticated/leave_.forecast'
import { Route as AuthenticatedLeaveEntitlementsRouteImport } from './routes/_authenticated/leave.entitlements'
import { Route as AuthenticatedCoordinatorRotaRouteImport } from './routes/_authenticated/coordinator.rota'
import { Route as AuthenticatedCoordinatorLeaveRouteImport } from './routes/_authenticated/coordinator.leave'
import { Route as AuthenticatedCoordinatorDutiesRouteImport } from './routes/_authenticated/coordinator.duties'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as AuthenticatedAdminTheatresRouteImport } from './routes/_authenticated/admin.theatres'
import { Route as AuthenticatedAdminTheatreGridRouteImport } from './routes/_authenticated/admin.theatre-grid'
import { Route as AuthenticatedAdminTheatreAliasesRouteImport } from './routes/_authenticated/admin.theatre-aliases'
import { Route as AuthenticatedAdminTcsAuditRouteImport } from './routes/_authenticated/admin.tcs-audit'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin.rules'
import { Route as AuthenticatedAdminRotaGapsRouteImport } from './routes/_authenticated/admin.rota-gaps'
import { Route as AuthenticatedAdminLeaveFairnessRouteImport } from './routes/_authenticated/admin.leave-fairness'
import { Route as AuthenticatedAdminJobPlansRouteImport } from './routes/_authenticated/admin.job-plans'
import { Route as AuthenticatedAdminExceptionsRouteImport } from './routes/_authenticated/admin.exceptions'
import { Route as AuthenticatedAdminDutyMappingsRouteImport } from './routes/_authenticated/admin.duty-mappings'
import { Route as AuthenticatedAdminDutyCategoriesRouteImport } from './routes/_authenticated/admin.duty-categories'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminClwrotaStepStatusRouteImport } from './routes/_authenticated/admin.clwrota-step-status'
import { Route as AuthenticatedAdminClwrotaStatusRouteImport } from './routes/_authenticated/admin.clwrota-status'
import { Route as AuthenticatedAdminClwrotaMetricsRouteImport } from './routes/_authenticated/admin.clwrota-metrics'
import { Route as AuthenticatedAdminAuditToolRouteImport } from './routes/_authenticated/admin.audit-tool'
import { Route as AuthenticatedAdminAccessRequestsRouteImport } from './routes/_authenticated/admin.access-requests'
import { Route as AuthenticatedAdminAbsenceRouteImport } from './routes/_authenticated/admin.absence'
import { Route as ApiPublicHooksSeedClwrotaVaultRouteImport } from './routes/api/public/hooks/seed-clwrota-vault'
import { Route as ApiPublicHooksRpcAccessAlertsRouteImport } from './routes/api/public/hooks/rpc-access-alerts'
import { Route as ApiPublicHooksPushDispatchRouteImport } from './routes/api/public/hooks/push-dispatch'
import { Route as ApiPublicHooksClwrotaSyncRouteImport } from './routes/api/public/hooks/clwrota-sync'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar/$token'
import { Route as AuthenticatedRobustnessDayDateRouteImport } from './routes/_authenticated/robustness.day.$date'
import { Route as AuthenticatedCalendarStaffStaffIdRouteImport } from './routes/_authenticated/calendar.staff.$staffId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditToolRoute = ApiAuditToolRouteImport.update({
  id: '/api/audit-tool',
  path: '/api/audit-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWellbeingRoute = AuthenticatedWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTraineesRoute = AuthenticatedTraineesRouteImport.update({
  id: '/trainees',
  path: '/trainees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecognitionRoute =
  AuthenticatedRecognitionRouteImport.update({
    id: '/recognition',
    path: '/recognition',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGlossaryRoute = AuthenticatedGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExceptionsRoute = AuthenticatedExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRobustnessIndexRoute =
  AuthenticatedRobustnessIndexRouteImport.update({
    id: '/robustness/',
    path: '/robustness/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTraineesStartDateAuditRoute =
  AuthenticatedTraineesStartDateAuditRouteImport.update({
    id: '/start-date-audit',
    path: '/start-date-audit',
    getParentRoute: () => AuthenticatedTraineesRoute,
  } as any)
const AuthenticatedTraineesStaffIdRoute =
  AuthenticatedTraineesStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedTraineesRoute,
  } as any)
const AuthenticatedStaffWorkingPatternsRoute =
  AuthenticatedStaffWorkingPatternsRouteImport.update({
    id: '/staff/working-patterns',
    path: '/staff/working-patterns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessSimulateRoute =
  AuthenticatedRobustnessSimulateRouteImport.update({
    id: '/robustness/simulate',
    path: '/robustness/simulate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessPoacAuditRoute =
  AuthenticatedRobustnessPoacAuditRouteImport.update({
    id: '/robustness/poac-audit',
    path: '/robustness/poac-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessListFeasibilityRoute =
  AuthenticatedRobustnessListFeasibilityRouteImport.update({
    id: '/robustness/list-feasibility',
    path: '/robustness/list-feasibility',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessLastMinuteChangesRoute =
  AuthenticatedRobustnessLastMinuteChangesRouteImport.update({
    id: '/robustness/last-minute-changes',
    path: '/robustness/last-minute-changes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessConsultantFeasibilityRoute =
  AuthenticatedRobustnessConsultantFeasibilityRouteImport.update({
    id: '/robustness/consultant-feasibility',
    path: '/robustness/consultant-feasibility',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRobustnessConsultantAuditsRoute =
  AuthenticatedRobustnessConsultantAuditsRouteImport.update({
    id: '/robustness/consultant-audits',
    path: '/robustness/consultant-audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaveForecastRoute =
  AuthenticatedLeaveForecastRouteImport.update({
    id: '/leave_/forecast',
    path: '/leave/forecast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaveEntitlementsRoute =
  AuthenticatedLeaveEntitlementsRouteImport.update({
    id: '/entitlements',
    path: '/entitlements',
    getParentRoute: () => AuthenticatedLeaveRoute,
  } as any)
const AuthenticatedCoordinatorRotaRoute =
  AuthenticatedCoordinatorRotaRouteImport.update({
    id: '/coordinator/rota',
    path: '/coordinator/rota',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoordinatorLeaveRoute =
  AuthenticatedCoordinatorLeaveRouteImport.update({
    id: '/coordinator/leave',
    path: '/coordinator/leave',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoordinatorDutiesRoute =
  AuthenticatedCoordinatorDutiesRouteImport.update({
    id: '/coordinator/duties',
    path: '/coordinator/duties',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedAdminTheatresRoute =
  AuthenticatedAdminTheatresRouteImport.update({
    id: '/admin/theatres',
    path: '/admin/theatres',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTheatreGridRoute =
  AuthenticatedAdminTheatreGridRouteImport.update({
    id: '/admin/theatre-grid',
    path: '/admin/theatre-grid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTheatreAliasesRoute =
  AuthenticatedAdminTheatreAliasesRouteImport.update({
    id: '/admin/theatre-aliases',
    path: '/admin/theatre-aliases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTcsAuditRoute =
  AuthenticatedAdminTcsAuditRouteImport.update({
    id: '/admin/tcs-audit',
    path: '/admin/tcs-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRotaGapsRoute =
  AuthenticatedAdminRotaGapsRouteImport.update({
    id: '/admin/rota-gaps',
    path: '/admin/rota-gaps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeaveFairnessRoute =
  AuthenticatedAdminLeaveFairnessRouteImport.update({
    id: '/admin/leave-fairness',
    path: '/admin/leave-fairness',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminJobPlansRoute =
  AuthenticatedAdminJobPlansRouteImport.update({
    id: '/admin/job-plans',
    path: '/admin/job-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExceptionsRoute =
  AuthenticatedAdminExceptionsRouteImport.update({
    id: '/admin/exceptions',
    path: '/admin/exceptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDutyMappingsRoute =
  AuthenticatedAdminDutyMappingsRouteImport.update({
    id: '/admin/duty-mappings',
    path: '/admin/duty-mappings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDutyCategoriesRoute =
  AuthenticatedAdminDutyCategoriesRouteImport.update({
    id: '/admin/duty-categories',
    path: '/admin/duty-categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClwrotaStepStatusRoute =
  AuthenticatedAdminClwrotaStepStatusRouteImport.update({
    id: '/admin/clwrota-step-status',
    path: '/admin/clwrota-step-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClwrotaStatusRoute =
  AuthenticatedAdminClwrotaStatusRouteImport.update({
    id: '/admin/clwrota-status',
    path: '/admin/clwrota-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClwrotaMetricsRoute =
  AuthenticatedAdminClwrotaMetricsRouteImport.update({
    id: '/admin/clwrota-metrics',
    path: '/admin/clwrota-metrics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditToolRoute =
  AuthenticatedAdminAuditToolRouteImport.update({
    id: '/admin/audit-tool',
    path: '/admin/audit-tool',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccessRequestsRoute =
  AuthenticatedAdminAccessRequestsRouteImport.update({
    id: '/admin/access-requests',
    path: '/admin/access-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAbsenceRoute =
  AuthenticatedAdminAbsenceRouteImport.update({
    id: '/admin/absence',
    path: '/admin/absence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksSeedClwrotaVaultRoute =
  ApiPublicHooksSeedClwrotaVaultRouteImport.update({
    id: '/api/public/hooks/seed-clwrota-vault',
    path: '/api/public/hooks/seed-clwrota-vault',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRpcAccessAlertsRoute =
  ApiPublicHooksRpcAccessAlertsRouteImport.update({
    id: '/api/public/hooks/rpc-access-alerts',
    path: '/api/public/hooks/rpc-access-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushDispatchRoute =
  ApiPublicHooksPushDispatchRouteImport.update({
    id: '/api/public/hooks/push-dispatch',
    path: '/api/public/hooks/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksClwrotaSyncRoute =
  ApiPublicHooksClwrotaSyncRouteImport.update({
    id: '/api/public/hooks/clwrota-sync',
    path: '/api/public/hooks/clwrota-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRobustnessDayDateRoute =
  AuthenticatedRobustnessDayDateRouteImport.update({
    id: '/robustness/day/$date',
    path: '/robustness/day/$date',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarStaffStaffIdRoute =
  AuthenticatedCalendarStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/exceptions': typeof AuthenticatedExceptionsRoute
  '/glossary': typeof AuthenticatedGlossaryRoute
  '/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/recognition': typeof AuthenticatedRecognitionRoute
  '/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/api/audit-tool': typeof ApiAuditToolRoute
  '/api/chat': typeof ApiChatRoute
  '/admin/absence': typeof AuthenticatedAdminAbsenceRoute
  '/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/admin/audit-tool': typeof AuthenticatedAdminAuditToolRoute
  '/admin/clwrota-metrics': typeof AuthenticatedAdminClwrotaMetricsRoute
  '/admin/clwrota-status': typeof AuthenticatedAdminClwrotaStatusRoute
  '/admin/clwrota-step-status': typeof AuthenticatedAdminClwrotaStepStatusRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/duty-categories': typeof AuthenticatedAdminDutyCategoriesRoute
  '/admin/duty-mappings': typeof AuthenticatedAdminDutyMappingsRoute
  '/admin/exceptions': typeof AuthenticatedAdminExceptionsRoute
  '/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/admin/leave-fairness': typeof AuthenticatedAdminLeaveFairnessRoute
  '/admin/rota-gaps': typeof AuthenticatedAdminRotaGapsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/admin/theatre-aliases': typeof AuthenticatedAdminTheatreAliasesRoute
  '/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/leave/entitlements': typeof AuthenticatedLeaveEntitlementsRoute
  '/leave/forecast': typeof AuthenticatedLeaveForecastRoute
  '/robustness/consultant-audits': typeof AuthenticatedRobustnessConsultantAuditsRoute
  '/robustness/consultant-feasibility': typeof AuthenticatedRobustnessConsultantFeasibilityRoute
  '/robustness/last-minute-changes': typeof AuthenticatedRobustnessLastMinuteChangesRoute
  '/robustness/list-feasibility': typeof AuthenticatedRobustnessListFeasibilityRoute
  '/robustness/poac-audit': typeof AuthenticatedRobustnessPoacAuditRoute
  '/robustness/simulate': typeof AuthenticatedRobustnessSimulateRoute
  '/staff/working-patterns': typeof AuthenticatedStaffWorkingPatternsRoute
  '/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/trainees/start-date-audit': typeof AuthenticatedTraineesStartDateAuditRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/robustness/': typeof AuthenticatedRobustnessIndexRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/robustness/day/$date': typeof AuthenticatedRobustnessDayDateRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/rpc-access-alerts': typeof ApiPublicHooksRpcAccessAlertsRoute
  '/api/public/hooks/seed-clwrota-vault': typeof ApiPublicHooksSeedClwrotaVaultRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/exceptions': typeof AuthenticatedExceptionsRoute
  '/glossary': typeof AuthenticatedGlossaryRoute
  '/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/recognition': typeof AuthenticatedRecognitionRoute
  '/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/wellbeing': typeof AuthenticatedWellbeingRoute
  '/api/audit-tool': typeof ApiAuditToolRoute
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/absence': typeof AuthenticatedAdminAbsenceRoute
  '/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/admin/audit-tool': typeof AuthenticatedAdminAuditToolRoute
  '/admin/clwrota-metrics': typeof AuthenticatedAdminClwrotaMetricsRoute
  '/admin/clwrota-status': typeof AuthenticatedAdminClwrotaStatusRoute
  '/admin/clwrota-step-status': typeof AuthenticatedAdminClwrotaStepStatusRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/duty-categories': typeof AuthenticatedAdminDutyCategoriesRoute
  '/admin/duty-mappings': typeof AuthenticatedAdminDutyMappingsRoute
  '/admin/exceptions': typeof AuthenticatedAdminExceptionsRoute
  '/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/admin/leave-fairness': typeof AuthenticatedAdminLeaveFairnessRoute
  '/admin/rota-gaps': typeof AuthenticatedAdminRotaGapsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/admin/theatre-aliases': typeof AuthenticatedAdminTheatreAliasesRoute
  '/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/leave/entitlements': typeof AuthenticatedLeaveEntitlementsRoute
  '/leave/forecast': typeof AuthenticatedLeaveForecastRoute
  '/robustness/consultant-audits': typeof AuthenticatedRobustnessConsultantAuditsRoute
  '/robustness/consultant-feasibility': typeof AuthenticatedRobustnessConsultantFeasibilityRoute
  '/robustness/last-minute-changes': typeof AuthenticatedRobustnessLastMinuteChangesRoute
  '/robustness/list-feasibility': typeof AuthenticatedRobustnessListFeasibilityRoute
  '/robustness/poac-audit': typeof AuthenticatedRobustnessPoacAuditRoute
  '/robustness/simulate': typeof AuthenticatedRobustnessSimulateRoute
  '/staff/working-patterns': typeof AuthenticatedStaffWorkingPatternsRoute
  '/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/trainees/start-date-audit': typeof AuthenticatedTraineesStartDateAuditRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/robustness': typeof AuthenticatedRobustnessIndexRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/robustness/day/$date': typeof AuthenticatedRobustnessDayDateRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/rpc-access-alerts': typeof ApiPublicHooksRpcAccessAlertsRoute
  '/api/public/hooks/seed-clwrota-vault': typeof ApiPublicHooksSeedClwrotaVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/exceptions': typeof AuthenticatedExceptionsRoute
  '/_authenticated/glossary': typeof AuthenticatedGlossaryRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/recognition': typeof AuthenticatedRecognitionRoute
  '/_authenticated/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/_authenticated/wellbeing': typeof AuthenticatedWellbeingRoute
  '/api/audit-tool': typeof ApiAuditToolRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/absence': typeof AuthenticatedAdminAbsenceRoute
  '/_authenticated/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/_authenticated/admin/audit-tool': typeof AuthenticatedAdminAuditToolRoute
  '/_authenticated/admin/clwrota-metrics': typeof AuthenticatedAdminClwrotaMetricsRoute
  '/_authenticated/admin/clwrota-status': typeof AuthenticatedAdminClwrotaStatusRoute
  '/_authenticated/admin/clwrota-step-status': typeof AuthenticatedAdminClwrotaStepStatusRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/duty-categories': typeof AuthenticatedAdminDutyCategoriesRoute
  '/_authenticated/admin/duty-mappings': typeof AuthenticatedAdminDutyMappingsRoute
  '/_authenticated/admin/exceptions': typeof AuthenticatedAdminExceptionsRoute
  '/_authenticated/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/_authenticated/admin/leave-fairness': typeof AuthenticatedAdminLeaveFairnessRoute
  '/_authenticated/admin/rota-gaps': typeof AuthenticatedAdminRotaGapsRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/_authenticated/admin/theatre-aliases': typeof AuthenticatedAdminTheatreAliasesRoute
  '/_authenticated/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/_authenticated/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/_authenticated/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/_authenticated/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/_authenticated/leave/entitlements': typeof AuthenticatedLeaveEntitlementsRoute
  '/_authenticated/leave_/forecast': typeof AuthenticatedLeaveForecastRoute
  '/_authenticated/robustness/consultant-audits': typeof AuthenticatedRobustnessConsultantAuditsRoute
  '/_authenticated/robustness/consultant-feasibility': typeof AuthenticatedRobustnessConsultantFeasibilityRoute
  '/_authenticated/robustness/last-minute-changes': typeof AuthenticatedRobustnessLastMinuteChangesRoute
  '/_authenticated/robustness/list-feasibility': typeof AuthenticatedRobustnessListFeasibilityRoute
  '/_authenticated/robustness/poac-audit': typeof AuthenticatedRobustnessPoacAuditRoute
  '/_authenticated/robustness/simulate': typeof AuthenticatedRobustnessSimulateRoute
  '/_authenticated/staff/working-patterns': typeof AuthenticatedStaffWorkingPatternsRoute
  '/_authenticated/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/_authenticated/trainees/start-date-audit': typeof AuthenticatedTraineesStartDateAuditRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/robustness/': typeof AuthenticatedRobustnessIndexRoute
  '/_authenticated/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/_authenticated/robustness/day/$date': typeof AuthenticatedRobustnessDayDateRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
  '/api/public/hooks/push-dispatch': typeof ApiPublicHooksPushDispatchRoute
  '/api/public/hooks/rpc-access-alerts': typeof ApiPublicHooksRpcAccessAlertsRoute
  '/api/public/hooks/seed-clwrota-vault': typeof ApiPublicHooksSeedClwrotaVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/calendar'
    | '/chat'
    | '/exceptions'
    | '/glossary'
    | '/leave'
    | '/me'
    | '/recognition'
    | '/trainees'
    | '/wellbeing'
    | '/api/audit-tool'
    | '/api/chat'
    | '/admin/absence'
    | '/admin/access-requests'
    | '/admin/audit-tool'
    | '/admin/clwrota-metrics'
    | '/admin/clwrota-status'
    | '/admin/clwrota-step-status'
    | '/admin/dashboard'
    | '/admin/duty-categories'
    | '/admin/duty-mappings'
    | '/admin/exceptions'
    | '/admin/job-plans'
    | '/admin/leave-fairness'
    | '/admin/rota-gaps'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tcs-audit'
    | '/admin/theatre-aliases'
    | '/admin/theatre-grid'
    | '/admin/theatres'
    | '/chat/$conversationId'
    | '/coordinator/duties'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/leave/entitlements'
    | '/leave/forecast'
    | '/robustness/consultant-audits'
    | '/robustness/consultant-feasibility'
    | '/robustness/last-minute-changes'
    | '/robustness/list-feasibility'
    | '/robustness/poac-audit'
    | '/robustness/simulate'
    | '/staff/working-patterns'
    | '/trainees/$staffId'
    | '/trainees/start-date-audit'
    | '/api/public/health'
    | '/chat/'
    | '/robustness/'
    | '/calendar/staff/$staffId'
    | '/robustness/day/$date'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/clwrota-sync'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/rpc-access-alerts'
    | '/api/public/hooks/seed-clwrota-vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/calendar'
    | '/exceptions'
    | '/glossary'
    | '/leave'
    | '/me'
    | '/recognition'
    | '/trainees'
    | '/wellbeing'
    | '/api/audit-tool'
    | '/api/chat'
    | '/'
    | '/admin/absence'
    | '/admin/access-requests'
    | '/admin/audit-tool'
    | '/admin/clwrota-metrics'
    | '/admin/clwrota-status'
    | '/admin/clwrota-step-status'
    | '/admin/dashboard'
    | '/admin/duty-categories'
    | '/admin/duty-mappings'
    | '/admin/exceptions'
    | '/admin/job-plans'
    | '/admin/leave-fairness'
    | '/admin/rota-gaps'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tcs-audit'
    | '/admin/theatre-aliases'
    | '/admin/theatre-grid'
    | '/admin/theatres'
    | '/chat/$conversationId'
    | '/coordinator/duties'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/leave/entitlements'
    | '/leave/forecast'
    | '/robustness/consultant-audits'
    | '/robustness/consultant-feasibility'
    | '/robustness/last-minute-changes'
    | '/robustness/list-feasibility'
    | '/robustness/poac-audit'
    | '/robustness/simulate'
    | '/staff/working-patterns'
    | '/trainees/$staffId'
    | '/trainees/start-date-audit'
    | '/api/public/health'
    | '/chat'
    | '/robustness'
    | '/calendar/staff/$staffId'
    | '/robustness/day/$date'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/clwrota-sync'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/rpc-access-alerts'
    | '/api/public/hooks/seed-clwrota-vault'
  id:
    | '__root__'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/exceptions'
    | '/_authenticated/glossary'
    | '/_authenticated/leave'
    | '/_authenticated/me'
    | '/_authenticated/recognition'
    | '/_authenticated/trainees'
    | '/_authenticated/wellbeing'
    | '/api/audit-tool'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/admin/absence'
    | '/_authenticated/admin/access-requests'
    | '/_authenticated/admin/audit-tool'
    | '/_authenticated/admin/clwrota-metrics'
    | '/_authenticated/admin/clwrota-status'
    | '/_authenticated/admin/clwrota-step-status'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/duty-categories'
    | '/_authenticated/admin/duty-mappings'
    | '/_authenticated/admin/exceptions'
    | '/_authenticated/admin/job-plans'
    | '/_authenticated/admin/leave-fairness'
    | '/_authenticated/admin/rota-gaps'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tcs-audit'
    | '/_authenticated/admin/theatre-aliases'
    | '/_authenticated/admin/theatre-grid'
    | '/_authenticated/admin/theatres'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/coordinator/duties'
    | '/_authenticated/coordinator/leave'
    | '/_authenticated/coordinator/rota'
    | '/_authenticated/leave/entitlements'
    | '/_authenticated/leave_/forecast'
    | '/_authenticated/robustness/consultant-audits'
    | '/_authenticated/robustness/consultant-feasibility'
    | '/_authenticated/robustness/last-minute-changes'
    | '/_authenticated/robustness/list-feasibility'
    | '/_authenticated/robustness/poac-audit'
    | '/_authenticated/robustness/simulate'
    | '/_authenticated/staff/working-patterns'
    | '/_authenticated/trainees/$staffId'
    | '/_authenticated/trainees/start-date-audit'
    | '/api/public/health'
    | '/_authenticated/chat/'
    | '/_authenticated/robustness/'
    | '/_authenticated/calendar/staff/$staffId'
    | '/_authenticated/robustness/day/$date'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/clwrota-sync'
    | '/api/public/hooks/push-dispatch'
    | '/api/public/hooks/rpc-access-alerts'
    | '/api/public/hooks/seed-clwrota-vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAuditToolRoute: typeof ApiAuditToolRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicHooksClwrotaSyncRoute: typeof ApiPublicHooksClwrotaSyncRoute
  ApiPublicHooksPushDispatchRoute: typeof ApiPublicHooksPushDispatchRoute
  ApiPublicHooksRpcAccessAlertsRoute: typeof ApiPublicHooksRpcAccessAlertsRoute
  ApiPublicHooksSeedClwrotaVaultRoute: typeof ApiPublicHooksSeedClwrotaVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-tool': {
      id: '/api/audit-tool'
      path: '/api/audit-tool'
      fullPath: '/api/audit-tool'
      preLoaderRoute: typeof ApiAuditToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wellbeing': {
      id: '/_authenticated/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof AuthenticatedWellbeingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainees': {
      id: '/_authenticated/trainees'
      path: '/trainees'
      fullPath: '/trainees'
      preLoaderRoute: typeof AuthenticatedTraineesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recognition': {
      id: '/_authenticated/recognition'
      path: '/recognition'
      fullPath: '/recognition'
      preLoaderRoute: typeof AuthenticatedRecognitionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/glossary': {
      id: '/_authenticated/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof AuthenticatedGlossaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exceptions': {
      id: '/_authenticated/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof AuthenticatedExceptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/': {
      id: '/_authenticated/robustness/'
      path: '/robustness'
      fullPath: '/robustness/'
      preLoaderRoute: typeof AuthenticatedRobustnessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trainees/start-date-audit': {
      id: '/_authenticated/trainees/start-date-audit'
      path: '/start-date-audit'
      fullPath: '/trainees/start-date-audit'
      preLoaderRoute: typeof AuthenticatedTraineesStartDateAuditRouteImport
      parentRoute: typeof AuthenticatedTraineesRoute
    }
    '/_authenticated/trainees/$staffId': {
      id: '/_authenticated/trainees/$staffId'
      path: '/$staffId'
      fullPath: '/trainees/$staffId'
      preLoaderRoute: typeof AuthenticatedTraineesStaffIdRouteImport
      parentRoute: typeof AuthenticatedTraineesRoute
    }
    '/_authenticated/staff/working-patterns': {
      id: '/_authenticated/staff/working-patterns'
      path: '/staff/working-patterns'
      fullPath: '/staff/working-patterns'
      preLoaderRoute: typeof AuthenticatedStaffWorkingPatternsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/simulate': {
      id: '/_authenticated/robustness/simulate'
      path: '/robustness/simulate'
      fullPath: '/robustness/simulate'
      preLoaderRoute: typeof AuthenticatedRobustnessSimulateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/poac-audit': {
      id: '/_authenticated/robustness/poac-audit'
      path: '/robustness/poac-audit'
      fullPath: '/robustness/poac-audit'
      preLoaderRoute: typeof AuthenticatedRobustnessPoacAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/list-feasibility': {
      id: '/_authenticated/robustness/list-feasibility'
      path: '/robustness/list-feasibility'
      fullPath: '/robustness/list-feasibility'
      preLoaderRoute: typeof AuthenticatedRobustnessListFeasibilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/last-minute-changes': {
      id: '/_authenticated/robustness/last-minute-changes'
      path: '/robustness/last-minute-changes'
      fullPath: '/robustness/last-minute-changes'
      preLoaderRoute: typeof AuthenticatedRobustnessLastMinuteChangesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/consultant-feasibility': {
      id: '/_authenticated/robustness/consultant-feasibility'
      path: '/robustness/consultant-feasibility'
      fullPath: '/robustness/consultant-feasibility'
      preLoaderRoute: typeof AuthenticatedRobustnessConsultantFeasibilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/robustness/consultant-audits': {
      id: '/_authenticated/robustness/consultant-audits'
      path: '/robustness/consultant-audits'
      fullPath: '/robustness/consultant-audits'
      preLoaderRoute: typeof AuthenticatedRobustnessConsultantAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave_/forecast': {
      id: '/_authenticated/leave_/forecast'
      path: '/leave/forecast'
      fullPath: '/leave/forecast'
      preLoaderRoute: typeof AuthenticatedLeaveForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave/entitlements': {
      id: '/_authenticated/leave/entitlements'
      path: '/entitlements'
      fullPath: '/leave/entitlements'
      preLoaderRoute: typeof AuthenticatedLeaveEntitlementsRouteImport
      parentRoute: typeof AuthenticatedLeaveRoute
    }
    '/_authenticated/coordinator/rota': {
      id: '/_authenticated/coordinator/rota'
      path: '/coordinator/rota'
      fullPath: '/coordinator/rota'
      preLoaderRoute: typeof AuthenticatedCoordinatorRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/leave': {
      id: '/_authenticated/coordinator/leave'
      path: '/coordinator/leave'
      fullPath: '/coordinator/leave'
      preLoaderRoute: typeof AuthenticatedCoordinatorLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/duties': {
      id: '/_authenticated/coordinator/duties'
      path: '/coordinator/duties'
      fullPath: '/coordinator/duties'
      preLoaderRoute: typeof AuthenticatedCoordinatorDutiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/admin/theatres': {
      id: '/_authenticated/admin/theatres'
      path: '/admin/theatres'
      fullPath: '/admin/theatres'
      preLoaderRoute: typeof AuthenticatedAdminTheatresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/theatre-grid': {
      id: '/_authenticated/admin/theatre-grid'
      path: '/admin/theatre-grid'
      fullPath: '/admin/theatre-grid'
      preLoaderRoute: typeof AuthenticatedAdminTheatreGridRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/theatre-aliases': {
      id: '/_authenticated/admin/theatre-aliases'
      path: '/admin/theatre-aliases'
      fullPath: '/admin/theatre-aliases'
      preLoaderRoute: typeof AuthenticatedAdminTheatreAliasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tcs-audit': {
      id: '/_authenticated/admin/tcs-audit'
      path: '/admin/tcs-audit'
      fullPath: '/admin/tcs-audit'
      preLoaderRoute: typeof AuthenticatedAdminTcsAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rota-gaps': {
      id: '/_authenticated/admin/rota-gaps'
      path: '/admin/rota-gaps'
      fullPath: '/admin/rota-gaps'
      preLoaderRoute: typeof AuthenticatedAdminRotaGapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leave-fairness': {
      id: '/_authenticated/admin/leave-fairness'
      path: '/admin/leave-fairness'
      fullPath: '/admin/leave-fairness'
      preLoaderRoute: typeof AuthenticatedAdminLeaveFairnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/job-plans': {
      id: '/_authenticated/admin/job-plans'
      path: '/admin/job-plans'
      fullPath: '/admin/job-plans'
      preLoaderRoute: typeof AuthenticatedAdminJobPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exceptions': {
      id: '/_authenticated/admin/exceptions'
      path: '/admin/exceptions'
      fullPath: '/admin/exceptions'
      preLoaderRoute: typeof AuthenticatedAdminExceptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/duty-mappings': {
      id: '/_authenticated/admin/duty-mappings'
      path: '/admin/duty-mappings'
      fullPath: '/admin/duty-mappings'
      preLoaderRoute: typeof AuthenticatedAdminDutyMappingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/duty-categories': {
      id: '/_authenticated/admin/duty-categories'
      path: '/admin/duty-categories'
      fullPath: '/admin/duty-categories'
      preLoaderRoute: typeof AuthenticatedAdminDutyCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clwrota-step-status': {
      id: '/_authenticated/admin/clwrota-step-status'
      path: '/admin/clwrota-step-status'
      fullPath: '/admin/clwrota-step-status'
      preLoaderRoute: typeof AuthenticatedAdminClwrotaStepStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clwrota-status': {
      id: '/_authenticated/admin/clwrota-status'
      path: '/admin/clwrota-status'
      fullPath: '/admin/clwrota-status'
      preLoaderRoute: typeof AuthenticatedAdminClwrotaStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clwrota-metrics': {
      id: '/_authenticated/admin/clwrota-metrics'
      path: '/admin/clwrota-metrics'
      fullPath: '/admin/clwrota-metrics'
      preLoaderRoute: typeof AuthenticatedAdminClwrotaMetricsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-tool': {
      id: '/_authenticated/admin/audit-tool'
      path: '/admin/audit-tool'
      fullPath: '/admin/audit-tool'
      preLoaderRoute: typeof AuthenticatedAdminAuditToolRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access-requests': {
      id: '/_authenticated/admin/access-requests'
      path: '/admin/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AuthenticatedAdminAccessRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/absence': {
      id: '/_authenticated/admin/absence'
      path: '/admin/absence'
      fullPath: '/admin/absence'
      preLoaderRoute: typeof AuthenticatedAdminAbsenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/seed-clwrota-vault': {
      id: '/api/public/hooks/seed-clwrota-vault'
      path: '/api/public/hooks/seed-clwrota-vault'
      fullPath: '/api/public/hooks/seed-clwrota-vault'
      preLoaderRoute: typeof ApiPublicHooksSeedClwrotaVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rpc-access-alerts': {
      id: '/api/public/hooks/rpc-access-alerts'
      path: '/api/public/hooks/rpc-access-alerts'
      fullPath: '/api/public/hooks/rpc-access-alerts'
      preLoaderRoute: typeof ApiPublicHooksRpcAccessAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/push-dispatch': {
      id: '/api/public/hooks/push-dispatch'
      path: '/api/public/hooks/push-dispatch'
      fullPath: '/api/public/hooks/push-dispatch'
      preLoaderRoute: typeof ApiPublicHooksPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/clwrota-sync': {
      id: '/api/public/hooks/clwrota-sync'
      path: '/api/public/hooks/clwrota-sync'
      fullPath: '/api/public/hooks/clwrota-sync'
      preLoaderRoute: typeof ApiPublicHooksClwrotaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/robustness/day/$date': {
      id: '/_authenticated/robustness/day/$date'
      path: '/robustness/day/$date'
      fullPath: '/robustness/day/$date'
      preLoaderRoute: typeof AuthenticatedRobustnessDayDateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/staff/$staffId': {
      id: '/_authenticated/calendar/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/calendar/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedCalendarStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
  }
}

interface AuthenticatedCalendarRouteChildren {
  AuthenticatedCalendarStaffStaffIdRoute: typeof AuthenticatedCalendarStaffStaffIdRoute
}

const AuthenticatedCalendarRouteChildren: AuthenticatedCalendarRouteChildren = {
  AuthenticatedCalendarStaffStaffIdRoute:
    AuthenticatedCalendarStaffStaffIdRoute,
}

const AuthenticatedCalendarRouteWithChildren =
  AuthenticatedCalendarRoute._addFileChildren(
    AuthenticatedCalendarRouteChildren,
  )

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedLeaveRouteChildren {
  AuthenticatedLeaveEntitlementsRoute: typeof AuthenticatedLeaveEntitlementsRoute
}

const AuthenticatedLeaveRouteChildren: AuthenticatedLeaveRouteChildren = {
  AuthenticatedLeaveEntitlementsRoute: AuthenticatedLeaveEntitlementsRoute,
}

const AuthenticatedLeaveRouteWithChildren =
  AuthenticatedLeaveRoute._addFileChildren(AuthenticatedLeaveRouteChildren)

interface AuthenticatedTraineesRouteChildren {
  AuthenticatedTraineesStaffIdRoute: typeof AuthenticatedTraineesStaffIdRoute
  AuthenticatedTraineesStartDateAuditRoute: typeof AuthenticatedTraineesStartDateAuditRoute
}

const AuthenticatedTraineesRouteChildren: AuthenticatedTraineesRouteChildren = {
  AuthenticatedTraineesStaffIdRoute: AuthenticatedTraineesStaffIdRoute,
  AuthenticatedTraineesStartDateAuditRoute:
    AuthenticatedTraineesStartDateAuditRoute,
}

const AuthenticatedTraineesRouteWithChildren =
  AuthenticatedTraineesRoute._addFileChildren(
    AuthenticatedTraineesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedExceptionsRoute: typeof AuthenticatedExceptionsRoute
  AuthenticatedGlossaryRoute: typeof AuthenticatedGlossaryRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedRecognitionRoute: typeof AuthenticatedRecognitionRoute
  AuthenticatedTraineesRoute: typeof AuthenticatedTraineesRouteWithChildren
  AuthenticatedWellbeingRoute: typeof AuthenticatedWellbeingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAbsenceRoute: typeof AuthenticatedAdminAbsenceRoute
  AuthenticatedAdminAccessRequestsRoute: typeof AuthenticatedAdminAccessRequestsRoute
  AuthenticatedAdminAuditToolRoute: typeof AuthenticatedAdminAuditToolRoute
  AuthenticatedAdminClwrotaMetricsRoute: typeof AuthenticatedAdminClwrotaMetricsRoute
  AuthenticatedAdminClwrotaStatusRoute: typeof AuthenticatedAdminClwrotaStatusRoute
  AuthenticatedAdminClwrotaStepStatusRoute: typeof AuthenticatedAdminClwrotaStepStatusRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDutyCategoriesRoute: typeof AuthenticatedAdminDutyCategoriesRoute
  AuthenticatedAdminDutyMappingsRoute: typeof AuthenticatedAdminDutyMappingsRoute
  AuthenticatedAdminExceptionsRoute: typeof AuthenticatedAdminExceptionsRoute
  AuthenticatedAdminJobPlansRoute: typeof AuthenticatedAdminJobPlansRoute
  AuthenticatedAdminLeaveFairnessRoute: typeof AuthenticatedAdminLeaveFairnessRoute
  AuthenticatedAdminRotaGapsRoute: typeof AuthenticatedAdminRotaGapsRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTcsAuditRoute: typeof AuthenticatedAdminTcsAuditRoute
  AuthenticatedAdminTheatreAliasesRoute: typeof AuthenticatedAdminTheatreAliasesRoute
  AuthenticatedAdminTheatreGridRoute: typeof AuthenticatedAdminTheatreGridRoute
  AuthenticatedAdminTheatresRoute: typeof AuthenticatedAdminTheatresRoute
  AuthenticatedCoordinatorDutiesRoute: typeof AuthenticatedCoordinatorDutiesRoute
  AuthenticatedCoordinatorLeaveRoute: typeof AuthenticatedCoordinatorLeaveRoute
  AuthenticatedCoordinatorRotaRoute: typeof AuthenticatedCoordinatorRotaRoute
  AuthenticatedLeaveForecastRoute: typeof AuthenticatedLeaveForecastRoute
  AuthenticatedRobustnessConsultantAuditsRoute: typeof AuthenticatedRobustnessConsultantAuditsRoute
  AuthenticatedRobustnessConsultantFeasibilityRoute: typeof AuthenticatedRobustnessConsultantFeasibilityRoute
  AuthenticatedRobustnessLastMinuteChangesRoute: typeof AuthenticatedRobustnessLastMinuteChangesRoute
  AuthenticatedRobustnessListFeasibilityRoute: typeof AuthenticatedRobustnessListFeasibilityRoute
  AuthenticatedRobustnessPoacAuditRoute: typeof AuthenticatedRobustnessPoacAuditRoute
  AuthenticatedRobustnessSimulateRoute: typeof AuthenticatedRobustnessSimulateRoute
  AuthenticatedStaffWorkingPatternsRoute: typeof AuthenticatedStaffWorkingPatternsRoute
  AuthenticatedRobustnessIndexRoute: typeof AuthenticatedRobustnessIndexRoute
  AuthenticatedRobustnessDayDateRoute: typeof AuthenticatedRobustnessDayDateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedExceptionsRoute: AuthenticatedExceptionsRoute,
  AuthenticatedGlossaryRoute: AuthenticatedGlossaryRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedRecognitionRoute: AuthenticatedRecognitionRoute,
  AuthenticatedTraineesRoute: AuthenticatedTraineesRouteWithChildren,
  AuthenticatedWellbeingRoute: AuthenticatedWellbeingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAbsenceRoute: AuthenticatedAdminAbsenceRoute,
  AuthenticatedAdminAccessRequestsRoute: AuthenticatedAdminAccessRequestsRoute,
  AuthenticatedAdminAuditToolRoute: AuthenticatedAdminAuditToolRoute,
  AuthenticatedAdminClwrotaMetricsRoute: AuthenticatedAdminClwrotaMetricsRoute,
  AuthenticatedAdminClwrotaStatusRoute: AuthenticatedAdminClwrotaStatusRoute,
  AuthenticatedAdminClwrotaStepStatusRoute:
    AuthenticatedAdminClwrotaStepStatusRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDutyCategoriesRoute: AuthenticatedAdminDutyCategoriesRoute,
  AuthenticatedAdminDutyMappingsRoute: AuthenticatedAdminDutyMappingsRoute,
  AuthenticatedAdminExceptionsRoute: AuthenticatedAdminExceptionsRoute,
  AuthenticatedAdminJobPlansRoute: AuthenticatedAdminJobPlansRoute,
  AuthenticatedAdminLeaveFairnessRoute: AuthenticatedAdminLeaveFairnessRoute,
  AuthenticatedAdminRotaGapsRoute: AuthenticatedAdminRotaGapsRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTcsAuditRoute: AuthenticatedAdminTcsAuditRoute,
  AuthenticatedAdminTheatreAliasesRoute: AuthenticatedAdminTheatreAliasesRoute,
  AuthenticatedAdminTheatreGridRoute: AuthenticatedAdminTheatreGridRoute,
  AuthenticatedAdminTheatresRoute: AuthenticatedAdminTheatresRoute,
  AuthenticatedCoordinatorDutiesRoute: AuthenticatedCoordinatorDutiesRoute,
  AuthenticatedCoordinatorLeaveRoute: AuthenticatedCoordinatorLeaveRoute,
  AuthenticatedCoordinatorRotaRoute: AuthenticatedCoordinatorRotaRoute,
  AuthenticatedLeaveForecastRoute: AuthenticatedLeaveForecastRoute,
  AuthenticatedRobustnessConsultantAuditsRoute:
    AuthenticatedRobustnessConsultantAuditsRoute,
  AuthenticatedRobustnessConsultantFeasibilityRoute:
    AuthenticatedRobustnessConsultantFeasibilityRoute,
  AuthenticatedRobustnessLastMinuteChangesRoute:
    AuthenticatedRobustnessLastMinuteChangesRoute,
  AuthenticatedRobustnessListFeasibilityRoute:
    AuthenticatedRobustnessListFeasibilityRoute,
  AuthenticatedRobustnessPoacAuditRoute: AuthenticatedRobustnessPoacAuditRoute,
  AuthenticatedRobustnessSimulateRoute: AuthenticatedRobustnessSimulateRoute,
  AuthenticatedStaffWorkingPatternsRoute:
    AuthenticatedStaffWorkingPatternsRoute,
  AuthenticatedRobustnessIndexRoute: AuthenticatedRobustnessIndexRoute,
  AuthenticatedRobustnessDayDateRoute: AuthenticatedRobustnessDayDateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAuditToolRoute: ApiAuditToolRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicHooksClwrotaSyncRoute: ApiPublicHooksClwrotaSyncRoute,
  ApiPublicHooksPushDispatchRoute: ApiPublicHooksPushDispatchRoute,
  ApiPublicHooksRpcAccessAlertsRoute: ApiPublicHooksRpcAccessAlertsRoute,
  ApiPublicHooksSeedClwrotaVaultRoute: ApiPublicHooksSeedClwrotaVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
