/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTraineesRouteImport } from './routes/_authenticated/trainees'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedTraineesStaffIdRouteImport } from './routes/_authenticated/trainees.$staffId'
import { Route as AuthenticatedLeaveForecastRouteImport } from './routes/_authenticated/leave.forecast'
import { Route as AuthenticatedCoordinatorRotaRouteImport } from './routes/_authenticated/coordinator.rota'
import { Route as AuthenticatedCoordinatorLeaveRouteImport } from './routes/_authenticated/coordinator.leave'
import { Route as AuthenticatedCoordinatorDutiesRouteImport } from './routes/_authenticated/coordinator.duties'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as AuthenticatedAdminTheatresRouteImport } from './routes/_authenticated/admin.theatres'
import { Route as AuthenticatedAdminTheatreGridRouteImport } from './routes/_authenticated/admin.theatre-grid'
import { Route as AuthenticatedAdminTcsAuditRouteImport } from './routes/_authenticated/admin.tcs-audit'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin.rules'
import { Route as AuthenticatedAdminJobPlansRouteImport } from './routes/_authenticated/admin.job-plans'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAccessRequestsRouteImport } from './routes/_authenticated/admin.access-requests'
import { Route as ApiPublicHooksClwrotaSyncRouteImport } from './routes/api/public/hooks/clwrota-sync'
import { Route as AuthenticatedCalendarStaffStaffIdRouteImport } from './routes/_authenticated/calendar.staff.$staffId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTraineesRoute = AuthenticatedTraineesRouteImport.update({
  id: '/trainees',
  path: '/trainees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedTraineesStaffIdRoute =
  AuthenticatedTraineesStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedTraineesRoute,
  } as any)
const AuthenticatedLeaveForecastRoute =
  AuthenticatedLeaveForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedLeaveRoute,
  } as any)
const AuthenticatedCoordinatorRotaRoute =
  AuthenticatedCoordinatorRotaRouteImport.update({
    id: '/coordinator/rota',
    path: '/coordinator/rota',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoordinatorLeaveRoute =
  AuthenticatedCoordinatorLeaveRouteImport.update({
    id: '/coordinator/leave',
    path: '/coordinator/leave',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoordinatorDutiesRoute =
  AuthenticatedCoordinatorDutiesRouteImport.update({
    id: '/coordinator/duties',
    path: '/coordinator/duties',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedAdminTheatresRoute =
  AuthenticatedAdminTheatresRouteImport.update({
    id: '/admin/theatres',
    path: '/admin/theatres',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTheatreGridRoute =
  AuthenticatedAdminTheatreGridRouteImport.update({
    id: '/admin/theatre-grid',
    path: '/admin/theatre-grid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTcsAuditRoute =
  AuthenticatedAdminTcsAuditRouteImport.update({
    id: '/admin/tcs-audit',
    path: '/admin/tcs-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminJobPlansRoute =
  AuthenticatedAdminJobPlansRouteImport.update({
    id: '/admin/job-plans',
    path: '/admin/job-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccessRequestsRoute =
  AuthenticatedAdminAccessRequestsRouteImport.update({
    id: '/admin/access-requests',
    path: '/admin/access-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksClwrotaSyncRoute =
  ApiPublicHooksClwrotaSyncRouteImport.update({
    id: '/api/public/hooks/clwrota-sync',
    path: '/api/public/hooks/clwrota-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCalendarStaffStaffIdRoute =
  AuthenticatedCalendarStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/leave/forecast': typeof AuthenticatedLeaveForecastRoute
  '/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/leave/forecast': typeof AuthenticatedLeaveForecastRoute
  '/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/leave': typeof AuthenticatedLeaveRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/trainees': typeof AuthenticatedTraineesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/access-requests': typeof AuthenticatedAdminAccessRequestsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/job-plans': typeof AuthenticatedAdminJobPlansRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tcs-audit': typeof AuthenticatedAdminTcsAuditRoute
  '/_authenticated/admin/theatre-grid': typeof AuthenticatedAdminTheatreGridRoute
  '/_authenticated/admin/theatres': typeof AuthenticatedAdminTheatresRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/coordinator/duties': typeof AuthenticatedCoordinatorDutiesRoute
  '/_authenticated/coordinator/leave': typeof AuthenticatedCoordinatorLeaveRoute
  '/_authenticated/coordinator/rota': typeof AuthenticatedCoordinatorRotaRoute
  '/_authenticated/leave/forecast': typeof AuthenticatedLeaveForecastRoute
  '/_authenticated/trainees/$staffId': typeof AuthenticatedTraineesStaffIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/calendar/staff/$staffId': typeof AuthenticatedCalendarStaffStaffIdRoute
  '/api/public/hooks/clwrota-sync': typeof ApiPublicHooksClwrotaSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/calendar'
    | '/chat'
    | '/leave'
    | '/me'
    | '/trainees'
    | '/api/chat'
    | '/admin/access-requests'
    | '/admin/dashboard'
    | '/admin/job-plans'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tcs-audit'
    | '/admin/theatre-grid'
    | '/admin/theatres'
    | '/chat/$conversationId'
    | '/coordinator/duties'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/leave/forecast'
    | '/trainees/$staffId'
    | '/chat/'
    | '/calendar/staff/$staffId'
    | '/api/public/hooks/clwrota-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/calendar'
    | '/leave'
    | '/me'
    | '/trainees'
    | '/api/chat'
    | '/'
    | '/admin/access-requests'
    | '/admin/dashboard'
    | '/admin/job-plans'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tcs-audit'
    | '/admin/theatre-grid'
    | '/admin/theatres'
    | '/chat/$conversationId'
    | '/coordinator/duties'
    | '/coordinator/leave'
    | '/coordinator/rota'
    | '/leave/forecast'
    | '/trainees/$staffId'
    | '/chat'
    | '/calendar/staff/$staffId'
    | '/api/public/hooks/clwrota-sync'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/leave'
    | '/_authenticated/me'
    | '/_authenticated/trainees'
    | '/api/chat'
    | '/_authenticated/'
    | '/_authenticated/admin/access-requests'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/job-plans'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tcs-audit'
    | '/_authenticated/admin/theatre-grid'
    | '/_authenticated/admin/theatres'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/coordinator/duties'
    | '/_authenticated/coordinator/leave'
    | '/_authenticated/coordinator/rota'
    | '/_authenticated/leave/forecast'
    | '/_authenticated/trainees/$staffId'
    | '/_authenticated/chat/'
    | '/_authenticated/calendar/staff/$staffId'
    | '/api/public/hooks/clwrota-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicHooksClwrotaSyncRoute: typeof ApiPublicHooksClwrotaSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trainees': {
      id: '/_authenticated/trainees'
      path: '/trainees'
      fullPath: '/trainees'
      preLoaderRoute: typeof AuthenticatedTraineesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/trainees/$staffId': {
      id: '/_authenticated/trainees/$staffId'
      path: '/$staffId'
      fullPath: '/trainees/$staffId'
      preLoaderRoute: typeof AuthenticatedTraineesStaffIdRouteImport
      parentRoute: typeof AuthenticatedTraineesRoute
    }
    '/_authenticated/leave/forecast': {
      id: '/_authenticated/leave/forecast'
      path: '/forecast'
      fullPath: '/leave/forecast'
      preLoaderRoute: typeof AuthenticatedLeaveForecastRouteImport
      parentRoute: typeof AuthenticatedLeaveRoute
    }
    '/_authenticated/coordinator/rota': {
      id: '/_authenticated/coordinator/rota'
      path: '/coordinator/rota'
      fullPath: '/coordinator/rota'
      preLoaderRoute: typeof AuthenticatedCoordinatorRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/leave': {
      id: '/_authenticated/coordinator/leave'
      path: '/coordinator/leave'
      fullPath: '/coordinator/leave'
      preLoaderRoute: typeof AuthenticatedCoordinatorLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordinator/duties': {
      id: '/_authenticated/coordinator/duties'
      path: '/coordinator/duties'
      fullPath: '/coordinator/duties'
      preLoaderRoute: typeof AuthenticatedCoordinatorDutiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/admin/theatres': {
      id: '/_authenticated/admin/theatres'
      path: '/admin/theatres'
      fullPath: '/admin/theatres'
      preLoaderRoute: typeof AuthenticatedAdminTheatresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/theatre-grid': {
      id: '/_authenticated/admin/theatre-grid'
      path: '/admin/theatre-grid'
      fullPath: '/admin/theatre-grid'
      preLoaderRoute: typeof AuthenticatedAdminTheatreGridRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tcs-audit': {
      id: '/_authenticated/admin/tcs-audit'
      path: '/admin/tcs-audit'
      fullPath: '/admin/tcs-audit'
      preLoaderRoute: typeof AuthenticatedAdminTcsAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/job-plans': {
      id: '/_authenticated/admin/job-plans'
      path: '/admin/job-plans'
      fullPath: '/admin/job-plans'
      preLoaderRoute: typeof AuthenticatedAdminJobPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access-requests': {
      id: '/_authenticated/admin/access-requests'
      path: '/admin/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AuthenticatedAdminAccessRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/clwrota-sync': {
      id: '/api/public/hooks/clwrota-sync'
      path: '/api/public/hooks/clwrota-sync'
      fullPath: '/api/public/hooks/clwrota-sync'
      preLoaderRoute: typeof ApiPublicHooksClwrotaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar/staff/$staffId': {
      id: '/_authenticated/calendar/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/calendar/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedCalendarStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedCalendarRoute
    }
  }
}

interface AuthenticatedCalendarRouteChildren {
  AuthenticatedCalendarStaffStaffIdRoute: typeof AuthenticatedCalendarStaffStaffIdRoute
}

const AuthenticatedCalendarRouteChildren: AuthenticatedCalendarRouteChildren = {
  AuthenticatedCalendarStaffStaffIdRoute:
    AuthenticatedCalendarStaffStaffIdRoute,
}

const AuthenticatedCalendarRouteWithChildren =
  AuthenticatedCalendarRoute._addFileChildren(
    AuthenticatedCalendarRouteChildren,
  )

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedLeaveRouteChildren {
  AuthenticatedLeaveForecastRoute: typeof AuthenticatedLeaveForecastRoute
}

const AuthenticatedLeaveRouteChildren: AuthenticatedLeaveRouteChildren = {
  AuthenticatedLeaveForecastRoute: AuthenticatedLeaveForecastRoute,
}

const AuthenticatedLeaveRouteWithChildren =
  AuthenticatedLeaveRoute._addFileChildren(AuthenticatedLeaveRouteChildren)

interface AuthenticatedTraineesRouteChildren {
  AuthenticatedTraineesStaffIdRoute: typeof AuthenticatedTraineesStaffIdRoute
}

const AuthenticatedTraineesRouteChildren: AuthenticatedTraineesRouteChildren = {
  AuthenticatedTraineesStaffIdRoute: AuthenticatedTraineesStaffIdRoute,
}

const AuthenticatedTraineesRouteWithChildren =
  AuthenticatedTraineesRoute._addFileChildren(
    AuthenticatedTraineesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedTraineesRoute: typeof AuthenticatedTraineesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAccessRequestsRoute: typeof AuthenticatedAdminAccessRequestsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminJobPlansRoute: typeof AuthenticatedAdminJobPlansRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTcsAuditRoute: typeof AuthenticatedAdminTcsAuditRoute
  AuthenticatedAdminTheatreGridRoute: typeof AuthenticatedAdminTheatreGridRoute
  AuthenticatedAdminTheatresRoute: typeof AuthenticatedAdminTheatresRoute
  AuthenticatedCoordinatorDutiesRoute: typeof AuthenticatedCoordinatorDutiesRoute
  AuthenticatedCoordinatorLeaveRoute: typeof AuthenticatedCoordinatorLeaveRoute
  AuthenticatedCoordinatorRotaRoute: typeof AuthenticatedCoordinatorRotaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedTraineesRoute: AuthenticatedTraineesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAccessRequestsRoute: AuthenticatedAdminAccessRequestsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminJobPlansRoute: AuthenticatedAdminJobPlansRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTcsAuditRoute: AuthenticatedAdminTcsAuditRoute,
  AuthenticatedAdminTheatreGridRoute: AuthenticatedAdminTheatreGridRoute,
  AuthenticatedAdminTheatresRoute: AuthenticatedAdminTheatresRoute,
  AuthenticatedCoordinatorDutiesRoute: AuthenticatedCoordinatorDutiesRoute,
  AuthenticatedCoordinatorLeaveRoute: AuthenticatedCoordinatorLeaveRoute,
  AuthenticatedCoordinatorRotaRoute: AuthenticatedCoordinatorRotaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicHooksClwrotaSyncRoute: ApiPublicHooksClwrotaSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
